-- Create the installers table
create table public.installers (
  id bigint generated by default as identity primary key,
  business_name text not null,
  contact_person text,
  city text not null,
  phone text not null,
  email text,
  experience_years int default 0,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.installers enable row level security;

-- Policy: Anyone can view the list of installers
create policy "Allow public read access" 
on public.installers for select 
using (true);

-- Policy: Anyone can apply to be an installer
create policy "Allow public insert" 
on public.installers for insert 
with check (true);

-- Add sample data for Chennai
insert into public.installers (business_name, contact_person, city, phone, email, website, experience_years, is_verified)
values 
('Chennai Rain Savers', 'Rajesh Kumar', 'Chennai', '+91 98765 43210', 'info@rainmatics.com', 'https://www.rainmatics.com', 5, true),
('AquaBlue Solutions', 'Sarah Thomas', 'Chennai', '+91 91234 56789', 'contact@aquablue.com', 'https://www.aquablueindia.com', 8, true),
('EcoHome Plumbers', 'Muthu', 'Chennai', '+91 99887 76655', 'hello@ecohome.in', 'https://www.ecohomeplumbers.in', 3, true);
